# Generated by Django 6.0.3 on 2026-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('selected_item', models.CharField(max_length=255, verbose_name='Выбранная услуга или товар')),
                ('desired_date', models.DateTimeField(verbose_name='Желаемая дата и время')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('PROCESSING', 'В обработке'), ('COMPLETED', 'Завершена')], default='NEW', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='Services/')),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
                ('profile', models.PositiveSmallIntegerField(verbose_name='Профиль')),
                ('diameter', models.PositiveSmallIntegerField(verbose_name='Диаметр (R)')),
                ('season', models.CharField(choices=[('SUMMER', 'Лето'), ('WINTER', 'Зима'), ('ALL_SEASON', 'Всесезонка')], max_length=20, verbose_name='Сезонность')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Наличие на складе (шт.)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Шина',
                'verbose_name_plural': 'Шины',
            },
        ),
    ]
